/**
 * Represents a single candidate infrastructure architecture.
 * 
 * Generated by the Architecture Designer stage, priced by the Cost Analyst,
 * validated by the Policy Validator, and evaluated by the Coordinator.
 * 
 * Each candidate is immutable once created - stages add information to it
 * but never modify existing fields.
 */
export interface CandidateArchitecture {
  /**
   * Unique identifier for this candidate.
   */
  readonly id: string;

  /**
   * Human-readable label (e.g., "ECS + PostgreSQL", "Lambda + DynamoDB").
   */
  readonly label: string;

  /**
   * Compute service type.
   */
  readonly compute: ComputeType;

  /**
   * Database service type.
   */
  readonly database: DatabaseType;

  /**
   * Whether a cache layer is included.
   */
  readonly cache: boolean;

  /**
   * Scaling strategy.
   */
  readonly scaling: ScalingType;

  /**
   * Instance type (e.g., "t4g.medium", "t3.large", "m5.large").
   */
  readonly instanceType: string;

  /**
   * Pricing information (populated by Cost Analyst).
   */
  readonly pricing?: CandidatePricing;

  /**
   * Policy validation results (populated by Policy Validator).
   */
  readonly policyChecks?: readonly PolicyCheckResult[];

  /**
   * If this candidate was rejected, the human-readable reason why.
   * Set by the Coordinator for non-recommended candidates.
   */
  readonly rejectionReason?: string;

  /**
   * Generated Terraform HCL (only for the recommended candidate).
   * Populated by the Coordinator after generate_terraform is called.
   */
  readonly terraform?: string;

  /**
   * Extensible metadata.
   */
  readonly metadata?: Record<string, unknown>;
}

/**
 * Compute service types supported in the MVP.
 */
export type ComputeType = "ec2" | "ecs_fargate" | "lambda" | "eks";

/**
 * Database service types supported in the MVP.
 */
export type DatabaseType = "postgresql" | "dynamodb";

/**
 * Scaling strategies.
 */
export type ScalingType = "fixed" | "auto";

/**
 * Pricing information for a single candidate architecture.
 * Computed by the Cost Analyst stage.
 */
export interface CandidatePricing {
  /**
   * Total monthly cost.
   */
  readonly monthlyCost: number;

  /**
   * Cost breakdown by category.
   */
  readonly breakdown: PricingBreakdown;

  /**
   * Currency unit (e.g., "INR", "USD").
   */
  readonly currency: string;
}

/**
 * Detailed cost breakdown by infrastructure component.
 */
export interface PricingBreakdown {
  /**
   * Compute costs (EC2, ECS, Lambda, etc.).
   */
  readonly compute: number;

  /**
   * Storage costs (RDS, EBS, S3, etc.).
   */
  readonly storage: number;

  /**
   * Network egress costs.
   */
  readonly networkEgress: number;

  /**
   * Other costs (load balancers, NAT gateways, etc.).
   */
  readonly other: number;
}

/**
 * Result of a single policy check against a candidate architecture.
 * Produced by the Policy Validator stage.
 */
export interface PolicyCheckResult {
  /**
   * Policy rule identifier.
   */
  readonly policyId: string;

  /**
   * Human-readable policy label.
   */
  readonly label: string;

  /**
   * Whether this candidate passed the policy check.
   */
  readonly passed: boolean;

  /**
   * Optional explanation of why the check failed.
   */
  readonly reason?: string;
}

/**
 * Collection of all candidate architectures for a session.
 * Maintained by the Architecture Designer and consumed by downstream stages.
 */
export interface ArchitectureSet {
  /**
   * All candidate architectures (typically exactly 3 for MVP).
   */
  readonly candidates: readonly CandidateArchitecture[];

  /**
   * ID of the recommended candidate (set by Coordinator).
   */
  readonly recommendedId?: string;
}
